# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' 
#' @param location/point
#' @param time
#' @param day
#' @param number
#' @param weight
#' 
#' @return a list including weekly estimates of entry and exist 
#'            together a visual barchart and  line chart  
#' 
#' @export
#' @examples
#' lts_extrapolate_numbers()
lts_extrapolate_numbers <- function(){
    
  
  
}
