# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' lts_setup
#' 
#' Apply a factorial design on all potential combination of time and location -
#' includes the possibiity to add ad-hoc constraints
#' 
#' The function will save an xlsform to be used for data collection
#'  preconfigured with the required  data universe
#' 
#' @param location (Bus terminal), point (bus gate) and 
#' @param time (timeshedule for bus).
#' @param constraint restriction ad-hic
#' @param filepath to save the xlsform 
#' @return result will be a list that will include all valid time/location combination within a day 
#' 
#' @export
#' @examples
#' lts_setup()
lts_setup <- function(){
    
}
