# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' lts_sample_shift
#' 
#' Draw the sample of ata collection shift to perform from the full 
#' location time universe 
#' 
#' NEXT - if stratified sampling then need to input data collected from previous
#'  shift - this will allow to calculate weight to apply for the next shift
#'   during the extrapolation
#' @param config_path path to the the configuration file
#' @param sample_size sample size neeeded
#' @param start_date enforce mdy "11-01-23"
#' @param end_date  enforce mdy  "11-30-23"
#' @param strata "low" "mid-low" "mid-high" "high" if strata is NULL then default is "low"
#' @param filename file to save the output 
#' @return selection of specific shift selected as sample (day / time / terminal / gate )
#' 
#' @export
#' @examples
#' ## day1_universe.xlsx
#' config_path <- system.file("day1_universe.xlsx", package = "LocationTimeSampling")
#'
#'
#' lts_sample_shift(config_path,
#'                  sample_size = 400,
#'                  start_date = "11-01-23", 
#'                  end_date = "11-30-23",
#'                  strata = "low",
#'                  filename = "sampleshift.xlsx")
lts_sample_shift <- function(config_path,
                             sample_size = 400,
                             start_date, 
                             end_date,
                             strata = "low",
                             filename){
  

 
config <-   readxl::read_excel(config_path, sheet = 1) |> 
  tidyr::separate(segment, 
                  into = c("terminal", "gate", "timeperiod"), 
                  sep = " - ")
  
universe <- 
  tidyr::expand_grid(day = lubridate::as_date(lubridate::mdy(start_date):lubridate::mdy(end_date)), 
 # tidyr::expand_grid(day = lubridate::make_date(2023, 11, 01:30), 
              config) |> 
  dplyr::transmute(day, timeperiod, terminal, gate,
            schedule = timeperiod,
            start = stringr::str_match(schedule, "^(.+?).00")[,2], 
            end = stringr::str_match(schedule, "a (.+).00$")[,2], 
            mid_schedule = (as.numeric(start) + as.numeric(end)) / 2) |> 
  dplyr::arrange(day, timeperiod, terminal, gate)

#sample_size <- 400 # turns for the whole month
srs_sample_size <- sample_size * .2
sys_sample_size <- sample_size * .8 # based on the June pilot

systematic_sample <- function(.x, n) {
  random_offset <- sample(nrow(.x)/n, 1)
    sampled_turns <- .x[round(seq(random_offset, 
                                  nrow(.x), 
                                  by = (nrow(.x)/n)), 0),]
}


# this is kosher for now, but we should do it differently in the future...
split_srs <- universe |> 
                dplyr::filter(strata == "low")

split_sys <- dplyr::anti_join(universe, split_srs)

sampled_turns_srs <- split_srs |> 
                      dplyr::arrange(day, timeperiod, terminal, gate) |>
                      systematic_sample(srs_sample_size)

sampled_turns_sys <- split_sys |> 
  systematic_sample(n = round(sys_sample_size, 0)) |> 
  dplyr::arrange(day, timeperiod, terminal, gate)

sampled_turns <- dplyr::bind_rows(sampled_turns_srs, sampled_turns_sys) |> 
                 dplyr::arrange(day, timeperiod, terminal, gate)

# check that the workload is distributed almost equally over the course of the month
#cat(sampled_turns |> dplyr::count(day) |> dplyr::count(n))

# month = substr(sampled_turns$day,6,7)
# year = substr(sampled_turns$day,1,4)
# today=today()
# export file
# filename <- paste(today," ", month, "-", year, "-", "(pps)", "timeperiods Conteo Tacna_.xlsx")
writexl::write_xlsx(sampled_turns, path=filename) 
    
}
